services:
    # PHP service
    php:
        container_name: inventory-sender
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            -   ./:/app
        ports:
            -   ${APP_PORT:-80}:8080
        networks:
            -   inventory-sender
        depends_on:
            database:
                condition: service_healthy
        restart: always

    # Database service
    database:
        container_name: inventory-sender-database
        image: postgres:16.3
        ports:
            -  ${FORWARD_DB_PORT:-5432}:5432
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - inventory-sender-database:/var/lib/postgresql/data
        networks:
            - inventory-sender
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
            interval: 3s    # Check every x seconds
            timeout: 2s     # Timeout if it takes longer than x  seconds
            retries: 5      # Mark unhealthy after 3 consecutive failures
        restart: always
networks:
    inventory-sender:
        driver: bridge

volumes:
    inventory-sender-database: ~
